# Generated by Django 5.1.3 on 2024-12-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
