# Generated by Django 5.1.3 on 2024-12-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0003_delete_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
