# Generated by Django 5.1.3 on 2024-12-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0004_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
