# Generated by Django 5.1.3 on 2024-12-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0005_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
