# Generated by Django 5.1.3 on 2024-12-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0008_rename_arrival_date_time_orders_arrival_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='image',
        ),
    ]
