# Generated by Django 5.1.3 on 2024-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0009_remove_orders_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='departure',
            field=models.DateTimeField(),
        ),
    ]
