# Generated by Django 5.1.3 on 2024-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0010_alter_orders_arrival_alter_orders_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='menu',
            field=models.CharField(default='default_menu', max_length=100),
        ),
    ]
