# Generated by Django 5.1.3 on 2024-12-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0013_ordering_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Ordering',
        ),
    ]
