# Generated by Django 5.1.3 on 2024-12-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0016_remove_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField()),
                ('image', models.ImageField(default='default_image.jpg', upload_to='images/')),
                ('guests', models.ManyToManyField(to='lexurapp.contact')),
            ],
        ),
    ]
