# Generated by Django 5.1.3 on 2024-12-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0018_delete_ordersmodel_remove_orders_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('menu', models.CharField(max_length=100)),
                ('guests', models.IntegerField()),
                ('conference', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
