# Generated by Django 5.1.3 on 2024-12-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0019_order_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
