# Generated by Django 5.1.3 on 2024-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexurapp', '0020_remove_imagemodel_price_alter_imagemodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otherchefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
